name: Run Tests on PR

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Preflight Checks and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run preflight checks (type check)
        run: mypy globe_news_scraper --install-types --non-interactive

      - name: Run tests
        run: pytest tests --junitxml=reports/test-results.xml

      - name: Upload test results as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/test-results.xml
